[package]
name = "pauli_tracker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[features]
circuit = []
# nightly-features (it's a little bit tricky because there's no #[cfg(nightly)]):
# when enabling --all-features, we usually do not want to enable the nightly features,
# therefore, we combine each nightly feature with a not(feature = "not-nightly); this
# works for example well when with the cargo.features = "all" configuration for
# rust-analyzer; the drawback is that we cannot use --all-features to enable all nightly
# features when compiling with the nightly toolchain; I think it's better to have
# --all-features working on stable than on nigthly
not-nightly = []
doc-build-nightly = []

[dependencies]

[package.metadata.docs.rs]
features = ["doc-build-nightly"]
