[package]
name = "python_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "pauli_tracker"
crate-type = ["cdylib"]

[dependencies]
lib = { package = "pauli_tracker", version = "0.3.1" }
pyo3 = "0.19.0"
