[package]
name = "xtask"
version = "0.1.0"
authors = ["Jannis Ruh <ruh.j81@gmail.com>"]
edition = "2021"
description = "Common dev tasks"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.3.0", features = ["derive"] }
proc = { path = "proc", package = "xtask_proc" }
