name: check
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: ./pauli_tracker

jobs:

  hack:
    name: hack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: cargo hack
        run: cargo hack check --feature-powerset --no-dev-deps

  msrv:
    name: msrv
    runs-on: ubuntu-latest
    env:
      msrv: 1.65.0
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable rust-$msrv
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: $msrv
      - name: Install nightly for -Zdirect-minimal-versions
        uses: dtolnay/rust-toolchain@nightly
      - name: Set default to stable
        run: rustup default stable
      - name: Generate the lockfile with the specified minimal versions
        run: cargo +nightly update -Zdirect-minimal-versions
      - name: cargo +$msrv check
        run: cargo check --locked --all-features

  clippy:
    name: ${{ matrix.toolchain }} / clippy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features
        env:
          RUSTFLAGS: "-Dwarnings"

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: cargo doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: "-Dwarnings --cfg docsrs"

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --check --package pauli_tracker

  semver:
    name: semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: install stable
        uses: dtolnay/rust-toolchain@stable
      - name: install semver-checks
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - name: cargo semver-checks
        run: cargo semver-checks

  public-deps:
    name: public-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: install nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: replace the manifest with the nightly manifest
        run: cp pauli_tracker/Cargo_nightly.toml pauli_tracker/Cargo.toml
      - name: cargo check
        run: cargo check --all-features
