name: safety
permissions:
  contents: read
on:
  push:
    branches: [main]
    paths: ["pauli_tracker/**"]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
defaults:
  run:
    working-directory: ./pauli_tracker

jobs:

  miri:
    name: miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - name: cargo miri test
        run: cargo miri test --all-features --lib --tests
      - name: cargo miri test docs
        run: cargo test --all-features --doc
